version: "3.3"

networks:
  dreamleague-network: {}

volumes:
  dreamleague-gameserver:
    name: 'dreamleague-gameserver'
  dreamleague-main-db:
    name: 'dreamleague-main-db'
  dreamleague-matches-db:
    name: 'dreamleague-matches-db'
  dreamleague-mongo-db:
    name: 'dreamleague-mongo-db'

services:
  gameserver:
    build:
      context: ./dreamleague.gameserver/docker
      dockerfile: Dockerfile
      args:
        METAMODURL: https://mms.alliedmods.net/mmsdrop/2.0/mmsource-2.0.0-git1282-linux.tar.gz
        CSSHARPURL: https://github.com/roflmuffin/CounterStrikeSharp/releases/download/v179/counterstrikesharp-with-runtime-build-179-linux-12485be.zip
        MATCHZYURL: https://github.com/shobhit-pathak/MatchZy/releases/download/0.7.0/matchzy-0.7.0.zip
    restart: always
    ports:
      - 27015:27015/tcp
      - 27015:27015/udp
      - 27020:27020/udp
    volumes:
      - dreamleague-gameserver:/home/steam/cs2server/
    networks:
      - dreamleague-network

  database-matches:
    build:
      context: ./dreamleague.matches.db/docker
      dockerfile: Dockerfile
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Password1234!
    ports:
      - 27017:27017
    volumes:
      - dreamleague-matches-db:/data/db
      - dreamleague-mongo-db:/data/configdb
    networks:
      - dreamleague-network

  database-main:
    build:
      context: ./dreamleague.main.db/docker
      dockerfile: Dockerfile
    restart: always
    depends_on:
      gameserver:
        condition: service_started
        restart: true
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1234!
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - dreamleague-main-db:/var/opt/mssql
    networks:
      - dreamleague-network

  api:
    build:
      context: ./dreamleague.api
      dockerfile: docker/Dockerfile
    depends_on:
      database-main:
        condition: service_healthy
        restart: true
      database-matches:
        condition: service_healthy
        restart: true
    environment:
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dockerapissl.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Password1234!
    ports:
      - 5000:5000
      - 5001:5001
    networks:
      - dreamleague-network
    volumes:
      - ~/.aspnet/https:/https:ro

  app:
    build:
      context: ./dreamleague.app
      dockerfile: docker/Dockerfile
    depends_on:
      database-main:
        condition: service_healthy
        restart: true
      database-matches:
        condition: service_healthy
        restart: true
      api:
        condition: service_started
        restart: true
    ports:
      - 3000:3000
    networks:
      - dreamleague-network
      

    