<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>5c67b144-18e4-433b-9c99-df62c74f9890</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\dreamleague.common\dreamleague.common.csproj" />
		<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.21.0" />
		<PackageReference Include="Microsoft.Azure.SignalR" Version="1.19.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.14.0" />
		<PackageReference Include="NewRelic.LogEnrichers.Serilog" Version="1.0.1" />
		<PackageReference Include="Serilog" Version="2.12.0" />
		<PackageReference Include="Serilog.Extensions.Hosting" Version="5.0.1" />
		<PackageReference Include="Serilog.Sinks.NewRelic" Version="2.0.0" />
		<PackageReference Include="Serilog.Sinks.NewRelic.Logs" Version="1.2.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\dreamleague.domain\dreamleague.domain.csproj" />
		<ProjectReference Include="..\dreamleague.hubs\dreamleague.hubs.csproj" />
		<ProjectReference Include="..\dreamleague.infrastructure\dreamleague.infrastructure.csproj" />
		<ProjectReference Include="..\dreamleague.shared\dreamleague.shared.csproj" />
		<ProjectReference Include="..\dreamleague.services\dreamleague.services.csproj" />
	</ItemGroup>
</Project>
