<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\dreamleague.common\dreamleague.common.csproj" />
    <PackageReference Include="Microsoft.Azure.SignalR" Version="1.19.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\dreamleague.domain\dreamleague.domain.csproj" />
    <ProjectReference Include="..\dreamleague.hubs\dreamleague.hubs.csproj" />
    <ProjectReference Include="..\dreamleague.infrastructure\dreamleague.infrastructure.csproj" />
    <ProjectReference Include="..\dreamleague.shared\dreamleague.shared.csproj" />
  </ItemGroup>

</Project>
